// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace Gazillion {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class ClientToGroupingManager {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    internal static pbd::MessageDescriptor internal__static_Gazillion_ClientIgnoredInvite__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::Gazillion.ClientIgnoredInvite, global::Gazillion.ClientIgnoredInvite.Builder> internal__static_Gazillion_ClientIgnoredInvite__FieldAccessorTable;
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static ClientToGroupingManager() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1DbGllbnRUb0dyb3VwaW5nTWFuYWdlci5wcm90bxIJR2F6aWxsaW9uIkMK", 
            "E0NsaWVudElnbm9yZWRJbnZpdGUSLAoRZGVjbGluaW5nUGxheWVySWQYASAC", 
          "KARSEWRlY2xpbmluZ1BsYXllcklk"));
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        internal__static_Gazillion_ClientIgnoredInvite__Descriptor = Descriptor.MessageTypes[0];
        internal__static_Gazillion_ClientIgnoredInvite__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::Gazillion.ClientIgnoredInvite, global::Gazillion.ClientIgnoredInvite.Builder>(internal__static_Gazillion_ClientIgnoredInvite__Descriptor,
                new string[] { "DecliningPlayerId", });
        pb::ExtensionRegistry registry = pb::ExtensionRegistry.CreateInstance();
        RegisterAllExtensions(registry);
        return registry;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          }, assigner);
    }
    #endregion
    
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class ClientIgnoredInvite : pb::GeneratedMessage<ClientIgnoredInvite, ClientIgnoredInvite.Builder> {
    private ClientIgnoredInvite() { }
    private static readonly ClientIgnoredInvite defaultInstance = new ClientIgnoredInvite().MakeReadOnly();
    private static readonly string[] _clientIgnoredInviteFieldNames = new string[] { "decliningPlayerId" };
    private static readonly uint[] _clientIgnoredInviteFieldTags = new uint[] { 8 };
    public static ClientIgnoredInvite DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override ClientIgnoredInvite DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override ClientIgnoredInvite ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::Gazillion.ClientToGroupingManager.internal__static_Gazillion_ClientIgnoredInvite__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<ClientIgnoredInvite, ClientIgnoredInvite.Builder> InternalFieldAccessors {
      get { return global::Gazillion.ClientToGroupingManager.internal__static_Gazillion_ClientIgnoredInvite__FieldAccessorTable; }
    }
    
    public const int DecliningPlayerIdFieldNumber = 1;
    private bool hasDecliningPlayerId;
    private ulong decliningPlayerId_;
    public bool HasDecliningPlayerId {
      get { return hasDecliningPlayerId; }
    }
    public ulong DecliningPlayerId {
      get { return decliningPlayerId_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasDecliningPlayerId) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      CalcSerializedSize();
      string[] field_names = _clientIgnoredInviteFieldNames;
      if (hasDecliningPlayerId) {
        output.WriteUInt64(1, field_names[0], DecliningPlayerId);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        return CalcSerializedSize();
      }
    }
    
    private int CalcSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (hasDecliningPlayerId) {
        size += pb::CodedOutputStream.ComputeUInt64Size(1, DecliningPlayerId);
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
    public static ClientIgnoredInvite ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static ClientIgnoredInvite ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static ClientIgnoredInvite ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static ClientIgnoredInvite ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static ClientIgnoredInvite ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static ClientIgnoredInvite ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static ClientIgnoredInvite ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static ClientIgnoredInvite ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static ClientIgnoredInvite ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static ClientIgnoredInvite ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private ClientIgnoredInvite MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(ClientIgnoredInvite prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<ClientIgnoredInvite, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(ClientIgnoredInvite cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private ClientIgnoredInvite result;
      
      private ClientIgnoredInvite PrepareBuilder() {
        if (resultIsReadOnly) {
          ClientIgnoredInvite original = result;
          result = new ClientIgnoredInvite();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override ClientIgnoredInvite MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::Gazillion.ClientIgnoredInvite.Descriptor; }
      }
      
      public override ClientIgnoredInvite DefaultInstanceForType {
        get { return global::Gazillion.ClientIgnoredInvite.DefaultInstance; }
      }
      
      public override ClientIgnoredInvite BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is ClientIgnoredInvite) {
          return MergeFrom((ClientIgnoredInvite) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(ClientIgnoredInvite other) {
        if (other == global::Gazillion.ClientIgnoredInvite.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasDecliningPlayerId) {
          DecliningPlayerId = other.DecliningPlayerId;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_clientIgnoredInviteFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _clientIgnoredInviteFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              result.hasDecliningPlayerId = input.ReadUInt64(ref result.decliningPlayerId_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasDecliningPlayerId {
        get { return result.hasDecliningPlayerId; }
      }
      public ulong DecliningPlayerId {
        get { return result.DecliningPlayerId; }
        set { SetDecliningPlayerId(value); }
      }
      public Builder SetDecliningPlayerId(ulong value) {
        PrepareBuilder();
        result.hasDecliningPlayerId = true;
        result.decliningPlayerId_ = value;
        return this;
      }
      public Builder ClearDecliningPlayerId() {
        PrepareBuilder();
        result.hasDecliningPlayerId = false;
        result.decliningPlayerId_ = 0UL;
        return this;
      }
    }
    static ClientIgnoredInvite() {
      object.ReferenceEquals(global::Gazillion.ClientToGroupingManager.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
