// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace Gazillion {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class AuthMessages {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    internal static pbd::MessageDescriptor internal__static_Gazillion_AuthTicket__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::Gazillion.AuthTicket, global::Gazillion.AuthTicket.Builder> internal__static_Gazillion_AuthTicket__FieldAccessorTable;
    internal static pbd::MessageDescriptor internal__static_Gazillion_ConsoleCreateAccountMessageResponse__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::Gazillion.ConsoleCreateAccountMessageResponse, global::Gazillion.ConsoleCreateAccountMessageResponse.Builder> internal__static_Gazillion_ConsoleCreateAccountMessageResponse__FieldAccessorTable;
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static AuthMessages() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJBdXRoTWVzc2FnZXMucHJvdG8SCUdhemlsbGlvbiKXCQoKQXV0aFRpY2tl", 
            "dBIeCgpzZXNzaW9uS2V5GAEgASgMUgpzZXNzaW9uS2V5EiIKDHNlc3Npb25U", 
            "b2tlbhgCIAEoDFIMc2Vzc2lvblRva2VuEhwKCXNlc3Npb25JZBgDIAIoBFIJ", 
            "c2Vzc2lvbklkEiIKDGVycm9yTWVzc2FnZRgEIAEoCVIMZXJyb3JNZXNzYWdl", 
            "EiYKDmZyb250ZW5kU2VydmVyGAUgASgJUg5mcm9udGVuZFNlcnZlchIiCgxm", 
            "cm9udGVuZFBvcnQYBiABKAlSDGZyb250ZW5kUG9ydBImCg5wbGF0Zm9ybVRp", 
            "Y2tldBgHIAEoCVIOcGxhdGZvcm1UaWNrZXQSKAoPcHJlc2FsZVB1cmNoYXNl", 
            "GAggASgIUg9wcmVzYWxlUHVyY2hhc2USFgoGdG9zdXJsGAkgASgJUgZ0b3N1", 
            "cmwSGAoHc3VjY2VzcxgKIAEoCFIHc3VjY2VzcxIYCgdoYXNuZXdzGAwgASgI", 
            "UgdoYXNuZXdzEhgKB25ld3N1cmwYDSABKAlSB25ld3N1cmwSJgoOaGFzUGVu", 
            "ZGluZ0dpZnQYDiABKAhSDmhhc1BlbmRpbmdHaWZ0EiYKDnBlbmRpbmdHaWZ0", 
            "VXJsGA8gASgJUg5wZW5kaW5nR2lmdFVybBIqChBoYXNWZXJpZmllZEVtYWls", 
            "GBAgASgIUhBoYXNWZXJpZmllZEVtYWlsEi4KD2lzQWxsb3dlZFRvQ2hhdBgR", 
            "IAEoCDoEdHJ1ZVIPaXNBbGxvd2VkVG9DaGF0Ej8KF2lzQWdlUmVzdHJpY3Rp", 
            "b25FbmFibGVkGBIgASgIOgVmYWxzZVIXaXNBZ2VSZXN0cmljdGlvbkVuYWJs", 
            "ZWQSOgoYYWdlUmVzdHJpY3Rpb25FbmRUaW1lVXRjGBMgASgDUhhhZ2VSZXN0", 
            "cmljdGlvbkVuZFRpbWVVdGMSRAodYWdlUmVzdHJpY3Rpb25XYXJuaW5nVGlt", 
            "ZVV0YzEYFCABKANSHWFnZVJlc3RyaWN0aW9uV2FybmluZ1RpbWVVdGMxEi4K", 
            "EmFnZVJlc3RyaWN0aW9uVHlwZRgVIAEoCVISYWdlUmVzdHJpY3Rpb25UeXBl", 
            "EkQKHWFnZVJlc3RyaWN0aW9uV2FybmluZ1RpbWVVdGMyGBYgASgDUh1hZ2VS", 
            "ZXN0cmljdGlvbldhcm5pbmdUaW1lVXRjMhJECh1hZ2VSZXN0cmljdGlvbldh", 
            "cm5pbmdUaW1lVXRjMxgXIAEoA1IdYWdlUmVzdHJpY3Rpb25XYXJuaW5nVGlt", 
            "ZVV0YzMSIAoLY291bnRyeUNvZGUYGCABKAlSC2NvdW50cnlDb2RlEiQKDWNv", 
            "bnRpbmVudENvZGUYGSABKAlSDWNvbnRpbmVudENvZGUSMAoTcHJlUmVxQ3Jl", 
            "YXRlQWNjb3VudBgaIAEoCFITcHJlUmVxQ3JlYXRlQWNjb3VudBIuChJwcmVS", 
            "ZXFSZW5hbWVQbGF5ZXIYGyABKAhSEnByZVJlcVJlbmFtZVBsYXllchIqChBw", 
            "cmVSZXFBY2NlcHREb2NzGBwgAygJUhBwcmVSZXFBY2NlcHREb2NzItUBCiND", 
            "b25zb2xlQ3JlYXRlQWNjb3VudE1lc3NhZ2VSZXNwb25zZRI8CgllcnJvckNv", 
            "ZGUYASABKA4yHi5HYXppbGxpb24uQXV0aFNlcnZlckVycm9yQ29kZVIJZXJy", 
            "b3JDb2RlEhoKCGVycm9yTXNnGAIgASgJUghlcnJvck1zZxIoCg9uYW1lU3Vn", 
            "Z2VzdGlvbnMYAyADKAlSD25hbWVTdWdnZXN0aW9ucxIqChBwcmVSZXFBY2Nl", 
            "cHREb2NzGAQgAygJUhBwcmVSZXFBY2NlcHREb2NzKm0KE0F1dGhTZXJ2ZXJF", 
            "cnJvckNvZGUSFgoSQVVUSF9FUlJPUl9TVUNDRVNTEAASHQoZQVVUSF9FUlJP", 
            "Ul9BQ0NPVU5UX0VYSVNUUxABEh8KG0FVVEhfRVJST1JfUExBWUVSTkFNRV9J", 
          "TlVTRRAC"));
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        internal__static_Gazillion_AuthTicket__Descriptor = Descriptor.MessageTypes[0];
        internal__static_Gazillion_AuthTicket__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::Gazillion.AuthTicket, global::Gazillion.AuthTicket.Builder>(internal__static_Gazillion_AuthTicket__Descriptor,
                new string[] { "SessionKey", "SessionToken", "SessionId", "ErrorMessage", "FrontendServer", "FrontendPort", "PlatformTicket", "PresalePurchase", "Tosurl", "Success", "Hasnews", "Newsurl", "HasPendingGift", "PendingGiftUrl", "HasVerifiedEmail", "IsAllowedToChat", "IsAgeRestrictionEnabled", "AgeRestrictionEndTimeUtc", "AgeRestrictionWarningTimeUtc1", "AgeRestrictionType", "AgeRestrictionWarningTimeUtc2", "AgeRestrictionWarningTimeUtc3", "CountryCode", "ContinentCode", "PreReqCreateAccount", "PreReqRenamePlayer", "PreReqAcceptDocs", });
        internal__static_Gazillion_ConsoleCreateAccountMessageResponse__Descriptor = Descriptor.MessageTypes[1];
        internal__static_Gazillion_ConsoleCreateAccountMessageResponse__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::Gazillion.ConsoleCreateAccountMessageResponse, global::Gazillion.ConsoleCreateAccountMessageResponse.Builder>(internal__static_Gazillion_ConsoleCreateAccountMessageResponse__Descriptor,
                new string[] { "ErrorCode", "ErrorMsg", "NameSuggestions", "PreReqAcceptDocs", });
        pb::ExtensionRegistry registry = pb::ExtensionRegistry.CreateInstance();
        RegisterAllExtensions(registry);
        return registry;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          }, assigner);
    }
    #endregion
    
  }
  #region Enums
  public enum AuthServerErrorCode {
    AUTH_ERROR_SUCCESS = 0,
    AUTH_ERROR_ACCOUNT_EXISTS = 1,
    AUTH_ERROR_PLAYERNAME_INUSE = 2,
  }
  
  #endregion
  
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class AuthTicket : pb::GeneratedMessage<AuthTicket, AuthTicket.Builder> {
    private AuthTicket() { }
    private static readonly AuthTicket defaultInstance = new AuthTicket().MakeReadOnly();
    private static readonly string[] _authTicketFieldNames = new string[] { "ageRestrictionEndTimeUtc", "ageRestrictionType", "ageRestrictionWarningTimeUtc1", "ageRestrictionWarningTimeUtc2", "ageRestrictionWarningTimeUtc3", "continentCode", "countryCode", "errorMessage", "frontendPort", "frontendServer", "hasPendingGift", "hasVerifiedEmail", "hasnews", "isAgeRestrictionEnabled", "isAllowedToChat", "newsurl", "pendingGiftUrl", "platformTicket", "preReqAcceptDocs", "preReqCreateAccount", "preReqRenamePlayer", "presalePurchase", "sessionId", "sessionKey", "sessionToken", "success", "tosurl" };
    private static readonly uint[] _authTicketFieldTags = new uint[] { 152, 170, 160, 176, 184, 202, 194, 34, 50, 42, 112, 128, 96, 144, 136, 106, 122, 58, 226, 208, 216, 64, 24, 10, 18, 80, 74 };
    public static AuthTicket DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override AuthTicket DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override AuthTicket ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::Gazillion.AuthMessages.internal__static_Gazillion_AuthTicket__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<AuthTicket, AuthTicket.Builder> InternalFieldAccessors {
      get { return global::Gazillion.AuthMessages.internal__static_Gazillion_AuthTicket__FieldAccessorTable; }
    }
    
    public const int SessionKeyFieldNumber = 1;
    private bool hasSessionKey;
    private pb::ByteString sessionKey_ = pb::ByteString.Empty;
    public bool HasSessionKey {
      get { return hasSessionKey; }
    }
    public pb::ByteString SessionKey {
      get { return sessionKey_; }
    }
    
    public const int SessionTokenFieldNumber = 2;
    private bool hasSessionToken;
    private pb::ByteString sessionToken_ = pb::ByteString.Empty;
    public bool HasSessionToken {
      get { return hasSessionToken; }
    }
    public pb::ByteString SessionToken {
      get { return sessionToken_; }
    }
    
    public const int SessionIdFieldNumber = 3;
    private bool hasSessionId;
    private ulong sessionId_;
    public bool HasSessionId {
      get { return hasSessionId; }
    }
    public ulong SessionId {
      get { return sessionId_; }
    }
    
    public const int ErrorMessageFieldNumber = 4;
    private bool hasErrorMessage;
    private string errorMessage_ = "";
    public bool HasErrorMessage {
      get { return hasErrorMessage; }
    }
    public string ErrorMessage {
      get { return errorMessage_; }
    }
    
    public const int FrontendServerFieldNumber = 5;
    private bool hasFrontendServer;
    private string frontendServer_ = "";
    public bool HasFrontendServer {
      get { return hasFrontendServer; }
    }
    public string FrontendServer {
      get { return frontendServer_; }
    }
    
    public const int FrontendPortFieldNumber = 6;
    private bool hasFrontendPort;
    private string frontendPort_ = "";
    public bool HasFrontendPort {
      get { return hasFrontendPort; }
    }
    public string FrontendPort {
      get { return frontendPort_; }
    }
    
    public const int PlatformTicketFieldNumber = 7;
    private bool hasPlatformTicket;
    private string platformTicket_ = "";
    public bool HasPlatformTicket {
      get { return hasPlatformTicket; }
    }
    public string PlatformTicket {
      get { return platformTicket_; }
    }
    
    public const int PresalePurchaseFieldNumber = 8;
    private bool hasPresalePurchase;
    private bool presalePurchase_;
    public bool HasPresalePurchase {
      get { return hasPresalePurchase; }
    }
    public bool PresalePurchase {
      get { return presalePurchase_; }
    }
    
    public const int TosurlFieldNumber = 9;
    private bool hasTosurl;
    private string tosurl_ = "";
    public bool HasTosurl {
      get { return hasTosurl; }
    }
    public string Tosurl {
      get { return tosurl_; }
    }
    
    public const int SuccessFieldNumber = 10;
    private bool hasSuccess;
    private bool success_;
    public bool HasSuccess {
      get { return hasSuccess; }
    }
    public bool Success {
      get { return success_; }
    }
    
    public const int HasnewsFieldNumber = 12;
    private bool hasHasnews;
    private bool hasnews_;
    public bool HasHasnews {
      get { return hasHasnews; }
    }
    public bool Hasnews {
      get { return hasnews_; }
    }
    
    public const int NewsurlFieldNumber = 13;
    private bool hasNewsurl;
    private string newsurl_ = "";
    public bool HasNewsurl {
      get { return hasNewsurl; }
    }
    public string Newsurl {
      get { return newsurl_; }
    }
    
    public const int HasPendingGiftFieldNumber = 14;
    private bool hasHasPendingGift;
    private bool hasPendingGift_;
    public bool HasHasPendingGift {
      get { return hasHasPendingGift; }
    }
    public bool HasPendingGift {
      get { return hasPendingGift_; }
    }
    
    public const int PendingGiftUrlFieldNumber = 15;
    private bool hasPendingGiftUrl;
    private string pendingGiftUrl_ = "";
    public bool HasPendingGiftUrl {
      get { return hasPendingGiftUrl; }
    }
    public string PendingGiftUrl {
      get { return pendingGiftUrl_; }
    }
    
    public const int HasVerifiedEmailFieldNumber = 16;
    private bool hasHasVerifiedEmail;
    private bool hasVerifiedEmail_;
    public bool HasHasVerifiedEmail {
      get { return hasHasVerifiedEmail; }
    }
    public bool HasVerifiedEmail {
      get { return hasVerifiedEmail_; }
    }
    
    public const int IsAllowedToChatFieldNumber = 17;
    private bool hasIsAllowedToChat;
    private bool isAllowedToChat_ = true;
    public bool HasIsAllowedToChat {
      get { return hasIsAllowedToChat; }
    }
    public bool IsAllowedToChat {
      get { return isAllowedToChat_; }
    }
    
    public const int IsAgeRestrictionEnabledFieldNumber = 18;
    private bool hasIsAgeRestrictionEnabled;
    private bool isAgeRestrictionEnabled_;
    public bool HasIsAgeRestrictionEnabled {
      get { return hasIsAgeRestrictionEnabled; }
    }
    public bool IsAgeRestrictionEnabled {
      get { return isAgeRestrictionEnabled_; }
    }
    
    public const int AgeRestrictionEndTimeUtcFieldNumber = 19;
    private bool hasAgeRestrictionEndTimeUtc;
    private long ageRestrictionEndTimeUtc_;
    public bool HasAgeRestrictionEndTimeUtc {
      get { return hasAgeRestrictionEndTimeUtc; }
    }
    public long AgeRestrictionEndTimeUtc {
      get { return ageRestrictionEndTimeUtc_; }
    }
    
    public const int AgeRestrictionWarningTimeUtc1FieldNumber = 20;
    private bool hasAgeRestrictionWarningTimeUtc1;
    private long ageRestrictionWarningTimeUtc1_;
    public bool HasAgeRestrictionWarningTimeUtc1 {
      get { return hasAgeRestrictionWarningTimeUtc1; }
    }
    public long AgeRestrictionWarningTimeUtc1 {
      get { return ageRestrictionWarningTimeUtc1_; }
    }
    
    public const int AgeRestrictionTypeFieldNumber = 21;
    private bool hasAgeRestrictionType;
    private string ageRestrictionType_ = "";
    public bool HasAgeRestrictionType {
      get { return hasAgeRestrictionType; }
    }
    public string AgeRestrictionType {
      get { return ageRestrictionType_; }
    }
    
    public const int AgeRestrictionWarningTimeUtc2FieldNumber = 22;
    private bool hasAgeRestrictionWarningTimeUtc2;
    private long ageRestrictionWarningTimeUtc2_;
    public bool HasAgeRestrictionWarningTimeUtc2 {
      get { return hasAgeRestrictionWarningTimeUtc2; }
    }
    public long AgeRestrictionWarningTimeUtc2 {
      get { return ageRestrictionWarningTimeUtc2_; }
    }
    
    public const int AgeRestrictionWarningTimeUtc3FieldNumber = 23;
    private bool hasAgeRestrictionWarningTimeUtc3;
    private long ageRestrictionWarningTimeUtc3_;
    public bool HasAgeRestrictionWarningTimeUtc3 {
      get { return hasAgeRestrictionWarningTimeUtc3; }
    }
    public long AgeRestrictionWarningTimeUtc3 {
      get { return ageRestrictionWarningTimeUtc3_; }
    }
    
    public const int CountryCodeFieldNumber = 24;
    private bool hasCountryCode;
    private string countryCode_ = "";
    public bool HasCountryCode {
      get { return hasCountryCode; }
    }
    public string CountryCode {
      get { return countryCode_; }
    }
    
    public const int ContinentCodeFieldNumber = 25;
    private bool hasContinentCode;
    private string continentCode_ = "";
    public bool HasContinentCode {
      get { return hasContinentCode; }
    }
    public string ContinentCode {
      get { return continentCode_; }
    }
    
    public const int PreReqCreateAccountFieldNumber = 26;
    private bool hasPreReqCreateAccount;
    private bool preReqCreateAccount_;
    public bool HasPreReqCreateAccount {
      get { return hasPreReqCreateAccount; }
    }
    public bool PreReqCreateAccount {
      get { return preReqCreateAccount_; }
    }
    
    public const int PreReqRenamePlayerFieldNumber = 27;
    private bool hasPreReqRenamePlayer;
    private bool preReqRenamePlayer_;
    public bool HasPreReqRenamePlayer {
      get { return hasPreReqRenamePlayer; }
    }
    public bool PreReqRenamePlayer {
      get { return preReqRenamePlayer_; }
    }
    
    public const int PreReqAcceptDocsFieldNumber = 28;
    private pbc::PopsicleList<string> preReqAcceptDocs_ = new pbc::PopsicleList<string>();
    public scg::IList<string> PreReqAcceptDocsList {
      get { return pbc::Lists.AsReadOnly(preReqAcceptDocs_); }
    }
    public int PreReqAcceptDocsCount {
      get { return preReqAcceptDocs_.Count; }
    }
    public string GetPreReqAcceptDocs(int index) {
      return preReqAcceptDocs_[index];
    }
    
    public override bool IsInitialized {
      get {
        if (!hasSessionId) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      CalcSerializedSize();
      string[] field_names = _authTicketFieldNames;
      if (hasSessionKey) {
        output.WriteBytes(1, field_names[23], SessionKey);
      }
      if (hasSessionToken) {
        output.WriteBytes(2, field_names[24], SessionToken);
      }
      if (hasSessionId) {
        output.WriteUInt64(3, field_names[22], SessionId);
      }
      if (hasErrorMessage) {
        output.WriteString(4, field_names[7], ErrorMessage);
      }
      if (hasFrontendServer) {
        output.WriteString(5, field_names[9], FrontendServer);
      }
      if (hasFrontendPort) {
        output.WriteString(6, field_names[8], FrontendPort);
      }
      if (hasPlatformTicket) {
        output.WriteString(7, field_names[17], PlatformTicket);
      }
      if (hasPresalePurchase) {
        output.WriteBool(8, field_names[21], PresalePurchase);
      }
      if (hasTosurl) {
        output.WriteString(9, field_names[26], Tosurl);
      }
      if (hasSuccess) {
        output.WriteBool(10, field_names[25], Success);
      }
      if (hasHasnews) {
        output.WriteBool(12, field_names[12], Hasnews);
      }
      if (hasNewsurl) {
        output.WriteString(13, field_names[15], Newsurl);
      }
      if (hasHasPendingGift) {
        output.WriteBool(14, field_names[10], HasPendingGift);
      }
      if (hasPendingGiftUrl) {
        output.WriteString(15, field_names[16], PendingGiftUrl);
      }
      if (hasHasVerifiedEmail) {
        output.WriteBool(16, field_names[11], HasVerifiedEmail);
      }
      if (hasIsAllowedToChat) {
        output.WriteBool(17, field_names[14], IsAllowedToChat);
      }
      if (hasIsAgeRestrictionEnabled) {
        output.WriteBool(18, field_names[13], IsAgeRestrictionEnabled);
      }
      if (hasAgeRestrictionEndTimeUtc) {
        output.WriteInt64(19, field_names[0], AgeRestrictionEndTimeUtc);
      }
      if (hasAgeRestrictionWarningTimeUtc1) {
        output.WriteInt64(20, field_names[2], AgeRestrictionWarningTimeUtc1);
      }
      if (hasAgeRestrictionType) {
        output.WriteString(21, field_names[1], AgeRestrictionType);
      }
      if (hasAgeRestrictionWarningTimeUtc2) {
        output.WriteInt64(22, field_names[3], AgeRestrictionWarningTimeUtc2);
      }
      if (hasAgeRestrictionWarningTimeUtc3) {
        output.WriteInt64(23, field_names[4], AgeRestrictionWarningTimeUtc3);
      }
      if (hasCountryCode) {
        output.WriteString(24, field_names[6], CountryCode);
      }
      if (hasContinentCode) {
        output.WriteString(25, field_names[5], ContinentCode);
      }
      if (hasPreReqCreateAccount) {
        output.WriteBool(26, field_names[19], PreReqCreateAccount);
      }
      if (hasPreReqRenamePlayer) {
        output.WriteBool(27, field_names[20], PreReqRenamePlayer);
      }
      if (preReqAcceptDocs_.Count > 0) {
        output.WriteStringArray(28, field_names[18], preReqAcceptDocs_);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        return CalcSerializedSize();
      }
    }
    
    private int CalcSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (hasSessionKey) {
        size += pb::CodedOutputStream.ComputeBytesSize(1, SessionKey);
      }
      if (hasSessionToken) {
        size += pb::CodedOutputStream.ComputeBytesSize(2, SessionToken);
      }
      if (hasSessionId) {
        size += pb::CodedOutputStream.ComputeUInt64Size(3, SessionId);
      }
      if (hasErrorMessage) {
        size += pb::CodedOutputStream.ComputeStringSize(4, ErrorMessage);
      }
      if (hasFrontendServer) {
        size += pb::CodedOutputStream.ComputeStringSize(5, FrontendServer);
      }
      if (hasFrontendPort) {
        size += pb::CodedOutputStream.ComputeStringSize(6, FrontendPort);
      }
      if (hasPlatformTicket) {
        size += pb::CodedOutputStream.ComputeStringSize(7, PlatformTicket);
      }
      if (hasPresalePurchase) {
        size += pb::CodedOutputStream.ComputeBoolSize(8, PresalePurchase);
      }
      if (hasTosurl) {
        size += pb::CodedOutputStream.ComputeStringSize(9, Tosurl);
      }
      if (hasSuccess) {
        size += pb::CodedOutputStream.ComputeBoolSize(10, Success);
      }
      if (hasHasnews) {
        size += pb::CodedOutputStream.ComputeBoolSize(12, Hasnews);
      }
      if (hasNewsurl) {
        size += pb::CodedOutputStream.ComputeStringSize(13, Newsurl);
      }
      if (hasHasPendingGift) {
        size += pb::CodedOutputStream.ComputeBoolSize(14, HasPendingGift);
      }
      if (hasPendingGiftUrl) {
        size += pb::CodedOutputStream.ComputeStringSize(15, PendingGiftUrl);
      }
      if (hasHasVerifiedEmail) {
        size += pb::CodedOutputStream.ComputeBoolSize(16, HasVerifiedEmail);
      }
      if (hasIsAllowedToChat) {
        size += pb::CodedOutputStream.ComputeBoolSize(17, IsAllowedToChat);
      }
      if (hasIsAgeRestrictionEnabled) {
        size += pb::CodedOutputStream.ComputeBoolSize(18, IsAgeRestrictionEnabled);
      }
      if (hasAgeRestrictionEndTimeUtc) {
        size += pb::CodedOutputStream.ComputeInt64Size(19, AgeRestrictionEndTimeUtc);
      }
      if (hasAgeRestrictionWarningTimeUtc1) {
        size += pb::CodedOutputStream.ComputeInt64Size(20, AgeRestrictionWarningTimeUtc1);
      }
      if (hasAgeRestrictionType) {
        size += pb::CodedOutputStream.ComputeStringSize(21, AgeRestrictionType);
      }
      if (hasAgeRestrictionWarningTimeUtc2) {
        size += pb::CodedOutputStream.ComputeInt64Size(22, AgeRestrictionWarningTimeUtc2);
      }
      if (hasAgeRestrictionWarningTimeUtc3) {
        size += pb::CodedOutputStream.ComputeInt64Size(23, AgeRestrictionWarningTimeUtc3);
      }
      if (hasCountryCode) {
        size += pb::CodedOutputStream.ComputeStringSize(24, CountryCode);
      }
      if (hasContinentCode) {
        size += pb::CodedOutputStream.ComputeStringSize(25, ContinentCode);
      }
      if (hasPreReqCreateAccount) {
        size += pb::CodedOutputStream.ComputeBoolSize(26, PreReqCreateAccount);
      }
      if (hasPreReqRenamePlayer) {
        size += pb::CodedOutputStream.ComputeBoolSize(27, PreReqRenamePlayer);
      }
      {
        int dataSize = 0;
        foreach (string element in PreReqAcceptDocsList) {
          dataSize += pb::CodedOutputStream.ComputeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 2 * preReqAcceptDocs_.Count;
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
    public static AuthTicket ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static AuthTicket ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static AuthTicket ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static AuthTicket ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static AuthTicket ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static AuthTicket ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static AuthTicket ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static AuthTicket ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static AuthTicket ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static AuthTicket ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private AuthTicket MakeReadOnly() {
      preReqAcceptDocs_.MakeReadOnly();
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(AuthTicket prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<AuthTicket, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(AuthTicket cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private AuthTicket result;
      
      private AuthTicket PrepareBuilder() {
        if (resultIsReadOnly) {
          AuthTicket original = result;
          result = new AuthTicket();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override AuthTicket MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::Gazillion.AuthTicket.Descriptor; }
      }
      
      public override AuthTicket DefaultInstanceForType {
        get { return global::Gazillion.AuthTicket.DefaultInstance; }
      }
      
      public override AuthTicket BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is AuthTicket) {
          return MergeFrom((AuthTicket) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(AuthTicket other) {
        if (other == global::Gazillion.AuthTicket.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasSessionKey) {
          SessionKey = other.SessionKey;
        }
        if (other.HasSessionToken) {
          SessionToken = other.SessionToken;
        }
        if (other.HasSessionId) {
          SessionId = other.SessionId;
        }
        if (other.HasErrorMessage) {
          ErrorMessage = other.ErrorMessage;
        }
        if (other.HasFrontendServer) {
          FrontendServer = other.FrontendServer;
        }
        if (other.HasFrontendPort) {
          FrontendPort = other.FrontendPort;
        }
        if (other.HasPlatformTicket) {
          PlatformTicket = other.PlatformTicket;
        }
        if (other.HasPresalePurchase) {
          PresalePurchase = other.PresalePurchase;
        }
        if (other.HasTosurl) {
          Tosurl = other.Tosurl;
        }
        if (other.HasSuccess) {
          Success = other.Success;
        }
        if (other.HasHasnews) {
          Hasnews = other.Hasnews;
        }
        if (other.HasNewsurl) {
          Newsurl = other.Newsurl;
        }
        if (other.HasHasPendingGift) {
          HasPendingGift = other.HasPendingGift;
        }
        if (other.HasPendingGiftUrl) {
          PendingGiftUrl = other.PendingGiftUrl;
        }
        if (other.HasHasVerifiedEmail) {
          HasVerifiedEmail = other.HasVerifiedEmail;
        }
        if (other.HasIsAllowedToChat) {
          IsAllowedToChat = other.IsAllowedToChat;
        }
        if (other.HasIsAgeRestrictionEnabled) {
          IsAgeRestrictionEnabled = other.IsAgeRestrictionEnabled;
        }
        if (other.HasAgeRestrictionEndTimeUtc) {
          AgeRestrictionEndTimeUtc = other.AgeRestrictionEndTimeUtc;
        }
        if (other.HasAgeRestrictionWarningTimeUtc1) {
          AgeRestrictionWarningTimeUtc1 = other.AgeRestrictionWarningTimeUtc1;
        }
        if (other.HasAgeRestrictionType) {
          AgeRestrictionType = other.AgeRestrictionType;
        }
        if (other.HasAgeRestrictionWarningTimeUtc2) {
          AgeRestrictionWarningTimeUtc2 = other.AgeRestrictionWarningTimeUtc2;
        }
        if (other.HasAgeRestrictionWarningTimeUtc3) {
          AgeRestrictionWarningTimeUtc3 = other.AgeRestrictionWarningTimeUtc3;
        }
        if (other.HasCountryCode) {
          CountryCode = other.CountryCode;
        }
        if (other.HasContinentCode) {
          ContinentCode = other.ContinentCode;
        }
        if (other.HasPreReqCreateAccount) {
          PreReqCreateAccount = other.PreReqCreateAccount;
        }
        if (other.HasPreReqRenamePlayer) {
          PreReqRenamePlayer = other.PreReqRenamePlayer;
        }
        if (other.preReqAcceptDocs_.Count != 0) {
          result.preReqAcceptDocs_.Add(other.preReqAcceptDocs_);
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_authTicketFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _authTicketFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasSessionKey = input.ReadBytes(ref result.sessionKey_);
              break;
            }
            case 18: {
              result.hasSessionToken = input.ReadBytes(ref result.sessionToken_);
              break;
            }
            case 24: {
              result.hasSessionId = input.ReadUInt64(ref result.sessionId_);
              break;
            }
            case 34: {
              result.hasErrorMessage = input.ReadString(ref result.errorMessage_);
              break;
            }
            case 42: {
              result.hasFrontendServer = input.ReadString(ref result.frontendServer_);
              break;
            }
            case 50: {
              result.hasFrontendPort = input.ReadString(ref result.frontendPort_);
              break;
            }
            case 58: {
              result.hasPlatformTicket = input.ReadString(ref result.platformTicket_);
              break;
            }
            case 64: {
              result.hasPresalePurchase = input.ReadBool(ref result.presalePurchase_);
              break;
            }
            case 74: {
              result.hasTosurl = input.ReadString(ref result.tosurl_);
              break;
            }
            case 80: {
              result.hasSuccess = input.ReadBool(ref result.success_);
              break;
            }
            case 96: {
              result.hasHasnews = input.ReadBool(ref result.hasnews_);
              break;
            }
            case 106: {
              result.hasNewsurl = input.ReadString(ref result.newsurl_);
              break;
            }
            case 112: {
              result.hasHasPendingGift = input.ReadBool(ref result.hasPendingGift_);
              break;
            }
            case 122: {
              result.hasPendingGiftUrl = input.ReadString(ref result.pendingGiftUrl_);
              break;
            }
            case 128: {
              result.hasHasVerifiedEmail = input.ReadBool(ref result.hasVerifiedEmail_);
              break;
            }
            case 136: {
              result.hasIsAllowedToChat = input.ReadBool(ref result.isAllowedToChat_);
              break;
            }
            case 144: {
              result.hasIsAgeRestrictionEnabled = input.ReadBool(ref result.isAgeRestrictionEnabled_);
              break;
            }
            case 152: {
              result.hasAgeRestrictionEndTimeUtc = input.ReadInt64(ref result.ageRestrictionEndTimeUtc_);
              break;
            }
            case 160: {
              result.hasAgeRestrictionWarningTimeUtc1 = input.ReadInt64(ref result.ageRestrictionWarningTimeUtc1_);
              break;
            }
            case 170: {
              result.hasAgeRestrictionType = input.ReadString(ref result.ageRestrictionType_);
              break;
            }
            case 176: {
              result.hasAgeRestrictionWarningTimeUtc2 = input.ReadInt64(ref result.ageRestrictionWarningTimeUtc2_);
              break;
            }
            case 184: {
              result.hasAgeRestrictionWarningTimeUtc3 = input.ReadInt64(ref result.ageRestrictionWarningTimeUtc3_);
              break;
            }
            case 194: {
              result.hasCountryCode = input.ReadString(ref result.countryCode_);
              break;
            }
            case 202: {
              result.hasContinentCode = input.ReadString(ref result.continentCode_);
              break;
            }
            case 208: {
              result.hasPreReqCreateAccount = input.ReadBool(ref result.preReqCreateAccount_);
              break;
            }
            case 216: {
              result.hasPreReqRenamePlayer = input.ReadBool(ref result.preReqRenamePlayer_);
              break;
            }
            case 226: {
              input.ReadStringArray(tag, field_name, result.preReqAcceptDocs_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasSessionKey {
        get { return result.hasSessionKey; }
      }
      public pb::ByteString SessionKey {
        get { return result.SessionKey; }
        set { SetSessionKey(value); }
      }
      public Builder SetSessionKey(pb::ByteString value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasSessionKey = true;
        result.sessionKey_ = value;
        return this;
      }
      public Builder ClearSessionKey() {
        PrepareBuilder();
        result.hasSessionKey = false;
        result.sessionKey_ = pb::ByteString.Empty;
        return this;
      }
      
      public bool HasSessionToken {
        get { return result.hasSessionToken; }
      }
      public pb::ByteString SessionToken {
        get { return result.SessionToken; }
        set { SetSessionToken(value); }
      }
      public Builder SetSessionToken(pb::ByteString value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasSessionToken = true;
        result.sessionToken_ = value;
        return this;
      }
      public Builder ClearSessionToken() {
        PrepareBuilder();
        result.hasSessionToken = false;
        result.sessionToken_ = pb::ByteString.Empty;
        return this;
      }
      
      public bool HasSessionId {
        get { return result.hasSessionId; }
      }
      public ulong SessionId {
        get { return result.SessionId; }
        set { SetSessionId(value); }
      }
      public Builder SetSessionId(ulong value) {
        PrepareBuilder();
        result.hasSessionId = true;
        result.sessionId_ = value;
        return this;
      }
      public Builder ClearSessionId() {
        PrepareBuilder();
        result.hasSessionId = false;
        result.sessionId_ = 0UL;
        return this;
      }
      
      public bool HasErrorMessage {
        get { return result.hasErrorMessage; }
      }
      public string ErrorMessage {
        get { return result.ErrorMessage; }
        set { SetErrorMessage(value); }
      }
      public Builder SetErrorMessage(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasErrorMessage = true;
        result.errorMessage_ = value;
        return this;
      }
      public Builder ClearErrorMessage() {
        PrepareBuilder();
        result.hasErrorMessage = false;
        result.errorMessage_ = "";
        return this;
      }
      
      public bool HasFrontendServer {
        get { return result.hasFrontendServer; }
      }
      public string FrontendServer {
        get { return result.FrontendServer; }
        set { SetFrontendServer(value); }
      }
      public Builder SetFrontendServer(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasFrontendServer = true;
        result.frontendServer_ = value;
        return this;
      }
      public Builder ClearFrontendServer() {
        PrepareBuilder();
        result.hasFrontendServer = false;
        result.frontendServer_ = "";
        return this;
      }
      
      public bool HasFrontendPort {
        get { return result.hasFrontendPort; }
      }
      public string FrontendPort {
        get { return result.FrontendPort; }
        set { SetFrontendPort(value); }
      }
      public Builder SetFrontendPort(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasFrontendPort = true;
        result.frontendPort_ = value;
        return this;
      }
      public Builder ClearFrontendPort() {
        PrepareBuilder();
        result.hasFrontendPort = false;
        result.frontendPort_ = "";
        return this;
      }
      
      public bool HasPlatformTicket {
        get { return result.hasPlatformTicket; }
      }
      public string PlatformTicket {
        get { return result.PlatformTicket; }
        set { SetPlatformTicket(value); }
      }
      public Builder SetPlatformTicket(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasPlatformTicket = true;
        result.platformTicket_ = value;
        return this;
      }
      public Builder ClearPlatformTicket() {
        PrepareBuilder();
        result.hasPlatformTicket = false;
        result.platformTicket_ = "";
        return this;
      }
      
      public bool HasPresalePurchase {
        get { return result.hasPresalePurchase; }
      }
      public bool PresalePurchase {
        get { return result.PresalePurchase; }
        set { SetPresalePurchase(value); }
      }
      public Builder SetPresalePurchase(bool value) {
        PrepareBuilder();
        result.hasPresalePurchase = true;
        result.presalePurchase_ = value;
        return this;
      }
      public Builder ClearPresalePurchase() {
        PrepareBuilder();
        result.hasPresalePurchase = false;
        result.presalePurchase_ = false;
        return this;
      }
      
      public bool HasTosurl {
        get { return result.hasTosurl; }
      }
      public string Tosurl {
        get { return result.Tosurl; }
        set { SetTosurl(value); }
      }
      public Builder SetTosurl(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasTosurl = true;
        result.tosurl_ = value;
        return this;
      }
      public Builder ClearTosurl() {
        PrepareBuilder();
        result.hasTosurl = false;
        result.tosurl_ = "";
        return this;
      }
      
      public bool HasSuccess {
        get { return result.hasSuccess; }
      }
      public bool Success {
        get { return result.Success; }
        set { SetSuccess(value); }
      }
      public Builder SetSuccess(bool value) {
        PrepareBuilder();
        result.hasSuccess = true;
        result.success_ = value;
        return this;
      }
      public Builder ClearSuccess() {
        PrepareBuilder();
        result.hasSuccess = false;
        result.success_ = false;
        return this;
      }
      
      public bool HasHasnews {
        get { return result.hasHasnews; }
      }
      public bool Hasnews {
        get { return result.Hasnews; }
        set { SetHasnews(value); }
      }
      public Builder SetHasnews(bool value) {
        PrepareBuilder();
        result.hasHasnews = true;
        result.hasnews_ = value;
        return this;
      }
      public Builder ClearHasnews() {
        PrepareBuilder();
        result.hasHasnews = false;
        result.hasnews_ = false;
        return this;
      }
      
      public bool HasNewsurl {
        get { return result.hasNewsurl; }
      }
      public string Newsurl {
        get { return result.Newsurl; }
        set { SetNewsurl(value); }
      }
      public Builder SetNewsurl(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasNewsurl = true;
        result.newsurl_ = value;
        return this;
      }
      public Builder ClearNewsurl() {
        PrepareBuilder();
        result.hasNewsurl = false;
        result.newsurl_ = "";
        return this;
      }
      
      public bool HasHasPendingGift {
        get { return result.hasHasPendingGift; }
      }
      public bool HasPendingGift {
        get { return result.HasPendingGift; }
        set { SetHasPendingGift(value); }
      }
      public Builder SetHasPendingGift(bool value) {
        PrepareBuilder();
        result.hasHasPendingGift = true;
        result.hasPendingGift_ = value;
        return this;
      }
      public Builder ClearHasPendingGift() {
        PrepareBuilder();
        result.hasHasPendingGift = false;
        result.hasPendingGift_ = false;
        return this;
      }
      
      public bool HasPendingGiftUrl {
        get { return result.hasPendingGiftUrl; }
      }
      public string PendingGiftUrl {
        get { return result.PendingGiftUrl; }
        set { SetPendingGiftUrl(value); }
      }
      public Builder SetPendingGiftUrl(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasPendingGiftUrl = true;
        result.pendingGiftUrl_ = value;
        return this;
      }
      public Builder ClearPendingGiftUrl() {
        PrepareBuilder();
        result.hasPendingGiftUrl = false;
        result.pendingGiftUrl_ = "";
        return this;
      }
      
      public bool HasHasVerifiedEmail {
        get { return result.hasHasVerifiedEmail; }
      }
      public bool HasVerifiedEmail {
        get { return result.HasVerifiedEmail; }
        set { SetHasVerifiedEmail(value); }
      }
      public Builder SetHasVerifiedEmail(bool value) {
        PrepareBuilder();
        result.hasHasVerifiedEmail = true;
        result.hasVerifiedEmail_ = value;
        return this;
      }
      public Builder ClearHasVerifiedEmail() {
        PrepareBuilder();
        result.hasHasVerifiedEmail = false;
        result.hasVerifiedEmail_ = false;
        return this;
      }
      
      public bool HasIsAllowedToChat {
        get { return result.hasIsAllowedToChat; }
      }
      public bool IsAllowedToChat {
        get { return result.IsAllowedToChat; }
        set { SetIsAllowedToChat(value); }
      }
      public Builder SetIsAllowedToChat(bool value) {
        PrepareBuilder();
        result.hasIsAllowedToChat = true;
        result.isAllowedToChat_ = value;
        return this;
      }
      public Builder ClearIsAllowedToChat() {
        PrepareBuilder();
        result.hasIsAllowedToChat = false;
        result.isAllowedToChat_ = true;
        return this;
      }
      
      public bool HasIsAgeRestrictionEnabled {
        get { return result.hasIsAgeRestrictionEnabled; }
      }
      public bool IsAgeRestrictionEnabled {
        get { return result.IsAgeRestrictionEnabled; }
        set { SetIsAgeRestrictionEnabled(value); }
      }
      public Builder SetIsAgeRestrictionEnabled(bool value) {
        PrepareBuilder();
        result.hasIsAgeRestrictionEnabled = true;
        result.isAgeRestrictionEnabled_ = value;
        return this;
      }
      public Builder ClearIsAgeRestrictionEnabled() {
        PrepareBuilder();
        result.hasIsAgeRestrictionEnabled = false;
        result.isAgeRestrictionEnabled_ = false;
        return this;
      }
      
      public bool HasAgeRestrictionEndTimeUtc {
        get { return result.hasAgeRestrictionEndTimeUtc; }
      }
      public long AgeRestrictionEndTimeUtc {
        get { return result.AgeRestrictionEndTimeUtc; }
        set { SetAgeRestrictionEndTimeUtc(value); }
      }
      public Builder SetAgeRestrictionEndTimeUtc(long value) {
        PrepareBuilder();
        result.hasAgeRestrictionEndTimeUtc = true;
        result.ageRestrictionEndTimeUtc_ = value;
        return this;
      }
      public Builder ClearAgeRestrictionEndTimeUtc() {
        PrepareBuilder();
        result.hasAgeRestrictionEndTimeUtc = false;
        result.ageRestrictionEndTimeUtc_ = 0L;
        return this;
      }
      
      public bool HasAgeRestrictionWarningTimeUtc1 {
        get { return result.hasAgeRestrictionWarningTimeUtc1; }
      }
      public long AgeRestrictionWarningTimeUtc1 {
        get { return result.AgeRestrictionWarningTimeUtc1; }
        set { SetAgeRestrictionWarningTimeUtc1(value); }
      }
      public Builder SetAgeRestrictionWarningTimeUtc1(long value) {
        PrepareBuilder();
        result.hasAgeRestrictionWarningTimeUtc1 = true;
        result.ageRestrictionWarningTimeUtc1_ = value;
        return this;
      }
      public Builder ClearAgeRestrictionWarningTimeUtc1() {
        PrepareBuilder();
        result.hasAgeRestrictionWarningTimeUtc1 = false;
        result.ageRestrictionWarningTimeUtc1_ = 0L;
        return this;
      }
      
      public bool HasAgeRestrictionType {
        get { return result.hasAgeRestrictionType; }
      }
      public string AgeRestrictionType {
        get { return result.AgeRestrictionType; }
        set { SetAgeRestrictionType(value); }
      }
      public Builder SetAgeRestrictionType(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasAgeRestrictionType = true;
        result.ageRestrictionType_ = value;
        return this;
      }
      public Builder ClearAgeRestrictionType() {
        PrepareBuilder();
        result.hasAgeRestrictionType = false;
        result.ageRestrictionType_ = "";
        return this;
      }
      
      public bool HasAgeRestrictionWarningTimeUtc2 {
        get { return result.hasAgeRestrictionWarningTimeUtc2; }
      }
      public long AgeRestrictionWarningTimeUtc2 {
        get { return result.AgeRestrictionWarningTimeUtc2; }
        set { SetAgeRestrictionWarningTimeUtc2(value); }
      }
      public Builder SetAgeRestrictionWarningTimeUtc2(long value) {
        PrepareBuilder();
        result.hasAgeRestrictionWarningTimeUtc2 = true;
        result.ageRestrictionWarningTimeUtc2_ = value;
        return this;
      }
      public Builder ClearAgeRestrictionWarningTimeUtc2() {
        PrepareBuilder();
        result.hasAgeRestrictionWarningTimeUtc2 = false;
        result.ageRestrictionWarningTimeUtc2_ = 0L;
        return this;
      }
      
      public bool HasAgeRestrictionWarningTimeUtc3 {
        get { return result.hasAgeRestrictionWarningTimeUtc3; }
      }
      public long AgeRestrictionWarningTimeUtc3 {
        get { return result.AgeRestrictionWarningTimeUtc3; }
        set { SetAgeRestrictionWarningTimeUtc3(value); }
      }
      public Builder SetAgeRestrictionWarningTimeUtc3(long value) {
        PrepareBuilder();
        result.hasAgeRestrictionWarningTimeUtc3 = true;
        result.ageRestrictionWarningTimeUtc3_ = value;
        return this;
      }
      public Builder ClearAgeRestrictionWarningTimeUtc3() {
        PrepareBuilder();
        result.hasAgeRestrictionWarningTimeUtc3 = false;
        result.ageRestrictionWarningTimeUtc3_ = 0L;
        return this;
      }
      
      public bool HasCountryCode {
        get { return result.hasCountryCode; }
      }
      public string CountryCode {
        get { return result.CountryCode; }
        set { SetCountryCode(value); }
      }
      public Builder SetCountryCode(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasCountryCode = true;
        result.countryCode_ = value;
        return this;
      }
      public Builder ClearCountryCode() {
        PrepareBuilder();
        result.hasCountryCode = false;
        result.countryCode_ = "";
        return this;
      }
      
      public bool HasContinentCode {
        get { return result.hasContinentCode; }
      }
      public string ContinentCode {
        get { return result.ContinentCode; }
        set { SetContinentCode(value); }
      }
      public Builder SetContinentCode(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasContinentCode = true;
        result.continentCode_ = value;
        return this;
      }
      public Builder ClearContinentCode() {
        PrepareBuilder();
        result.hasContinentCode = false;
        result.continentCode_ = "";
        return this;
      }
      
      public bool HasPreReqCreateAccount {
        get { return result.hasPreReqCreateAccount; }
      }
      public bool PreReqCreateAccount {
        get { return result.PreReqCreateAccount; }
        set { SetPreReqCreateAccount(value); }
      }
      public Builder SetPreReqCreateAccount(bool value) {
        PrepareBuilder();
        result.hasPreReqCreateAccount = true;
        result.preReqCreateAccount_ = value;
        return this;
      }
      public Builder ClearPreReqCreateAccount() {
        PrepareBuilder();
        result.hasPreReqCreateAccount = false;
        result.preReqCreateAccount_ = false;
        return this;
      }
      
      public bool HasPreReqRenamePlayer {
        get { return result.hasPreReqRenamePlayer; }
      }
      public bool PreReqRenamePlayer {
        get { return result.PreReqRenamePlayer; }
        set { SetPreReqRenamePlayer(value); }
      }
      public Builder SetPreReqRenamePlayer(bool value) {
        PrepareBuilder();
        result.hasPreReqRenamePlayer = true;
        result.preReqRenamePlayer_ = value;
        return this;
      }
      public Builder ClearPreReqRenamePlayer() {
        PrepareBuilder();
        result.hasPreReqRenamePlayer = false;
        result.preReqRenamePlayer_ = false;
        return this;
      }
      
      public pbc::IPopsicleList<string> PreReqAcceptDocsList {
        get { return PrepareBuilder().preReqAcceptDocs_; }
      }
      public int PreReqAcceptDocsCount {
        get { return result.PreReqAcceptDocsCount; }
      }
      public string GetPreReqAcceptDocs(int index) {
        return result.GetPreReqAcceptDocs(index);
      }
      public Builder SetPreReqAcceptDocs(int index, string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.preReqAcceptDocs_[index] = value;
        return this;
      }
      public Builder AddPreReqAcceptDocs(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.preReqAcceptDocs_.Add(value);
        return this;
      }
      public Builder AddRangePreReqAcceptDocs(scg::IEnumerable<string> values) {
        PrepareBuilder();
        result.preReqAcceptDocs_.Add(values);
        return this;
      }
      public Builder ClearPreReqAcceptDocs() {
        PrepareBuilder();
        result.preReqAcceptDocs_.Clear();
        return this;
      }
    }
    static AuthTicket() {
      object.ReferenceEquals(global::Gazillion.AuthMessages.Descriptor, null);
    }
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class ConsoleCreateAccountMessageResponse : pb::GeneratedMessage<ConsoleCreateAccountMessageResponse, ConsoleCreateAccountMessageResponse.Builder> {
    private ConsoleCreateAccountMessageResponse() { }
    private static readonly ConsoleCreateAccountMessageResponse defaultInstance = new ConsoleCreateAccountMessageResponse().MakeReadOnly();
    private static readonly string[] _consoleCreateAccountMessageResponseFieldNames = new string[] { "errorCode", "errorMsg", "nameSuggestions", "preReqAcceptDocs" };
    private static readonly uint[] _consoleCreateAccountMessageResponseFieldTags = new uint[] { 8, 18, 26, 34 };
    public static ConsoleCreateAccountMessageResponse DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override ConsoleCreateAccountMessageResponse DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override ConsoleCreateAccountMessageResponse ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::Gazillion.AuthMessages.internal__static_Gazillion_ConsoleCreateAccountMessageResponse__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<ConsoleCreateAccountMessageResponse, ConsoleCreateAccountMessageResponse.Builder> InternalFieldAccessors {
      get { return global::Gazillion.AuthMessages.internal__static_Gazillion_ConsoleCreateAccountMessageResponse__FieldAccessorTable; }
    }
    
    public const int ErrorCodeFieldNumber = 1;
    private bool hasErrorCode;
    private global::Gazillion.AuthServerErrorCode errorCode_ = global::Gazillion.AuthServerErrorCode.AUTH_ERROR_SUCCESS;
    public bool HasErrorCode {
      get { return hasErrorCode; }
    }
    public global::Gazillion.AuthServerErrorCode ErrorCode {
      get { return errorCode_; }
    }
    
    public const int ErrorMsgFieldNumber = 2;
    private bool hasErrorMsg;
    private string errorMsg_ = "";
    public bool HasErrorMsg {
      get { return hasErrorMsg; }
    }
    public string ErrorMsg {
      get { return errorMsg_; }
    }
    
    public const int NameSuggestionsFieldNumber = 3;
    private pbc::PopsicleList<string> nameSuggestions_ = new pbc::PopsicleList<string>();
    public scg::IList<string> NameSuggestionsList {
      get { return pbc::Lists.AsReadOnly(nameSuggestions_); }
    }
    public int NameSuggestionsCount {
      get { return nameSuggestions_.Count; }
    }
    public string GetNameSuggestions(int index) {
      return nameSuggestions_[index];
    }
    
    public const int PreReqAcceptDocsFieldNumber = 4;
    private pbc::PopsicleList<string> preReqAcceptDocs_ = new pbc::PopsicleList<string>();
    public scg::IList<string> PreReqAcceptDocsList {
      get { return pbc::Lists.AsReadOnly(preReqAcceptDocs_); }
    }
    public int PreReqAcceptDocsCount {
      get { return preReqAcceptDocs_.Count; }
    }
    public string GetPreReqAcceptDocs(int index) {
      return preReqAcceptDocs_[index];
    }
    
    public override bool IsInitialized {
      get {
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      CalcSerializedSize();
      string[] field_names = _consoleCreateAccountMessageResponseFieldNames;
      if (hasErrorCode) {
        output.WriteEnum(1, field_names[0], (int) ErrorCode, ErrorCode);
      }
      if (hasErrorMsg) {
        output.WriteString(2, field_names[1], ErrorMsg);
      }
      if (nameSuggestions_.Count > 0) {
        output.WriteStringArray(3, field_names[2], nameSuggestions_);
      }
      if (preReqAcceptDocs_.Count > 0) {
        output.WriteStringArray(4, field_names[3], preReqAcceptDocs_);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        return CalcSerializedSize();
      }
    }
    
    private int CalcSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      
      size = 0;
      if (hasErrorCode) {
        size += pb::CodedOutputStream.ComputeEnumSize(1, (int) ErrorCode);
      }
      if (hasErrorMsg) {
        size += pb::CodedOutputStream.ComputeStringSize(2, ErrorMsg);
      }
      {
        int dataSize = 0;
        foreach (string element in NameSuggestionsList) {
          dataSize += pb::CodedOutputStream.ComputeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * nameSuggestions_.Count;
      }
      {
        int dataSize = 0;
        foreach (string element in PreReqAcceptDocsList) {
          dataSize += pb::CodedOutputStream.ComputeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * preReqAcceptDocs_.Count;
      }
      size += UnknownFields.SerializedSize;
      memoizedSerializedSize = size;
      return size;
    }
    public static ConsoleCreateAccountMessageResponse ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static ConsoleCreateAccountMessageResponse ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static ConsoleCreateAccountMessageResponse ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static ConsoleCreateAccountMessageResponse ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static ConsoleCreateAccountMessageResponse ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static ConsoleCreateAccountMessageResponse ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static ConsoleCreateAccountMessageResponse ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static ConsoleCreateAccountMessageResponse ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static ConsoleCreateAccountMessageResponse ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static ConsoleCreateAccountMessageResponse ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private ConsoleCreateAccountMessageResponse MakeReadOnly() {
      nameSuggestions_.MakeReadOnly();
      preReqAcceptDocs_.MakeReadOnly();
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(ConsoleCreateAccountMessageResponse prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<ConsoleCreateAccountMessageResponse, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(ConsoleCreateAccountMessageResponse cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private ConsoleCreateAccountMessageResponse result;
      
      private ConsoleCreateAccountMessageResponse PrepareBuilder() {
        if (resultIsReadOnly) {
          ConsoleCreateAccountMessageResponse original = result;
          result = new ConsoleCreateAccountMessageResponse();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override ConsoleCreateAccountMessageResponse MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::Gazillion.ConsoleCreateAccountMessageResponse.Descriptor; }
      }
      
      public override ConsoleCreateAccountMessageResponse DefaultInstanceForType {
        get { return global::Gazillion.ConsoleCreateAccountMessageResponse.DefaultInstance; }
      }
      
      public override ConsoleCreateAccountMessageResponse BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is ConsoleCreateAccountMessageResponse) {
          return MergeFrom((ConsoleCreateAccountMessageResponse) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(ConsoleCreateAccountMessageResponse other) {
        if (other == global::Gazillion.ConsoleCreateAccountMessageResponse.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasErrorCode) {
          ErrorCode = other.ErrorCode;
        }
        if (other.HasErrorMsg) {
          ErrorMsg = other.ErrorMsg;
        }
        if (other.nameSuggestions_.Count != 0) {
          result.nameSuggestions_.Add(other.nameSuggestions_);
        }
        if (other.preReqAcceptDocs_.Count != 0) {
          result.preReqAcceptDocs_.Add(other.preReqAcceptDocs_);
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_consoleCreateAccountMessageResponseFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _consoleCreateAccountMessageResponseFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              object unknown;
              if(input.ReadEnum(ref result.errorCode_, out unknown)) {
                result.hasErrorCode = true;
              } else if(unknown is int) {
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                unknownFields.MergeVarintField(1, (ulong)(int)unknown);
              }
              break;
            }
            case 18: {
              result.hasErrorMsg = input.ReadString(ref result.errorMsg_);
              break;
            }
            case 26: {
              input.ReadStringArray(tag, field_name, result.nameSuggestions_);
              break;
            }
            case 34: {
              input.ReadStringArray(tag, field_name, result.preReqAcceptDocs_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasErrorCode {
       get { return result.hasErrorCode; }
      }
      public global::Gazillion.AuthServerErrorCode ErrorCode {
        get { return result.ErrorCode; }
        set { SetErrorCode(value); }
      }
      public Builder SetErrorCode(global::Gazillion.AuthServerErrorCode value) {
        PrepareBuilder();
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder ClearErrorCode() {
        PrepareBuilder();
        result.hasErrorCode = false;
        result.errorCode_ = global::Gazillion.AuthServerErrorCode.AUTH_ERROR_SUCCESS;
        return this;
      }
      
      public bool HasErrorMsg {
        get { return result.hasErrorMsg; }
      }
      public string ErrorMsg {
        get { return result.ErrorMsg; }
        set { SetErrorMsg(value); }
      }
      public Builder SetErrorMsg(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasErrorMsg = true;
        result.errorMsg_ = value;
        return this;
      }
      public Builder ClearErrorMsg() {
        PrepareBuilder();
        result.hasErrorMsg = false;
        result.errorMsg_ = "";
        return this;
      }
      
      public pbc::IPopsicleList<string> NameSuggestionsList {
        get { return PrepareBuilder().nameSuggestions_; }
      }
      public int NameSuggestionsCount {
        get { return result.NameSuggestionsCount; }
      }
      public string GetNameSuggestions(int index) {
        return result.GetNameSuggestions(index);
      }
      public Builder SetNameSuggestions(int index, string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.nameSuggestions_[index] = value;
        return this;
      }
      public Builder AddNameSuggestions(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.nameSuggestions_.Add(value);
        return this;
      }
      public Builder AddRangeNameSuggestions(scg::IEnumerable<string> values) {
        PrepareBuilder();
        result.nameSuggestions_.Add(values);
        return this;
      }
      public Builder ClearNameSuggestions() {
        PrepareBuilder();
        result.nameSuggestions_.Clear();
        return this;
      }
      
      public pbc::IPopsicleList<string> PreReqAcceptDocsList {
        get { return PrepareBuilder().preReqAcceptDocs_; }
      }
      public int PreReqAcceptDocsCount {
        get { return result.PreReqAcceptDocsCount; }
      }
      public string GetPreReqAcceptDocs(int index) {
        return result.GetPreReqAcceptDocs(index);
      }
      public Builder SetPreReqAcceptDocs(int index, string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.preReqAcceptDocs_[index] = value;
        return this;
      }
      public Builder AddPreReqAcceptDocs(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.preReqAcceptDocs_.Add(value);
        return this;
      }
      public Builder AddRangePreReqAcceptDocs(scg::IEnumerable<string> values) {
        PrepareBuilder();
        result.preReqAcceptDocs_.Add(values);
        return this;
      }
      public Builder ClearPreReqAcceptDocs() {
        PrepareBuilder();
        result.preReqAcceptDocs_.Clear();
        return this;
      }
    }
    static ConsoleCreateAccountMessageResponse() {
      object.ReferenceEquals(global::Gazillion.AuthMessages.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
