// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace Gazillion {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class GlobalEventsCommon {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static GlobalEventsCommon() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhHbG9iYWxFdmVudHNDb21tb24ucHJvdG8SCUdhemlsbGlvbip7ChVHbG9i", 
            "YWxFdmVudFVwZGF0ZVR5cGUSIAocZUdsb2JhbEV2ZW50VXBkYXRlX0V2ZW50", 
            "RGF0YRAAEiIKHmVHbG9iYWxFdmVudFVwZGF0ZV9MZWFkZXJib2FyZBABEhwK", 
          "GGVHbG9iYWxFdmVudFVwZGF0ZV9Db3VudBAC"));
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        return null;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          }, assigner);
    }
    #endregion
    
  }
  #region Enums
  public enum GlobalEventUpdateType {
    eGlobalEventUpdate_EventData = 0,
    eGlobalEventUpdate_Leaderboard = 1,
    eGlobalEventUpdate_Count = 2,
  }
  
  #endregion
  
}

#endregion Designer generated code
